"""add sale fields

Revision ID: 2104a3b5b35d
Revises: 
Create Date: 2026-06-26 15:10:12.676206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2104a3b5b35d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('purchase_price', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('profit', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('sale_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sale_date')
    op.drop_column('sales', 'profit')
    op.drop_column('sales', 'purchase_price')
    # ### end Alembic commands ###
